DEVICE_ID = 1
SAMPLE_RATE = 48000
CHANNELS = 2

AUDIO_FILE = "grabacion.wav"

SILENCE_THRESHOLD = 0.0005
SILENCE_SECONDS = 2.5
MIN_RECORD_SECONDS = 4
MAX_RECORD_SECONDS = 15
BLOCK_SECONDS = 0.2

OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "phi3:latest"

WHISPER_MODEL = "small"
WHISPER_LANGUAGE = "es"
APP_LANGUAGE = "es"